
/* X11 data types */
A(UTF8_STRING)
A(_XROOTPMAP_ID)

/* old WM spec */
A(WM_STATE)
A(WM_CLASS)
A(WM_DELETE_WINDOW)
A(WM_PROTOCOLS)

/* new NET spec */

A(_NET_WORKAREA)
A(_NET_CLIENT_LIST)
A(_NET_CLIENT_LIST_STACKING)
A(_NET_NUMBER_OF_DESKTOPS)
A(_NET_CURRENT_DESKTOP)
A(_NET_DESKTOP_VIEWPORT)
A(_NET_DESKTOP_NAMES)
A(_NET_ACTIVE_WINDOW)
A(_NET_CLOSE_WINDOW)
A(_NET_SHOWING_DESKTOP)
A(_NET_SUPPORTED)

A(_NET_WM_STATE)
A(_NET_WM_STATE_MODAL)
A(_NET_WM_STATE_STICKY)
A(_NET_WM_STATE_MAXIMIZED_VERT)
A(_NET_WM_STATE_MAXIMIZED_HORZ)
A(_NET_WM_STATE_SHADED)
A(_NET_WM_STATE_SKIP_TASKBAR)
A(_NET_WM_STATE_SKIP_PAGER)
A(_NET_WM_STATE_HIDDEN)
A(_NET_WM_STATE_FULLSCREEN)
A(_NET_WM_STATE_ABOVE)
A(_NET_WM_STATE_BELOW)
A(_NET_WM_STATE_DEMANDS_ATTENTION)

A(_OB_WM_STATE_UNDECORATED)

A(_NET_WM_WINDOW_TYPE)
A(_NET_WM_WINDOW_TYPE_DESKTOP)
A(_NET_WM_WINDOW_TYPE_DOCK)
A(_NET_WM_WINDOW_TYPE_TOOLBAR)
A(_NET_WM_WINDOW_TYPE_MENU)
A(_NET_WM_WINDOW_TYPE_UTILITY)
A(_NET_WM_WINDOW_TYPE_SPLASH)
A(_NET_WM_WINDOW_TYPE_DIALOG)
A(_NET_WM_WINDOW_TYPE_NORMAL)
A(_NET_WM_DESKTOP)
A(_NET_WM_PID)
A(_NET_WM_NAME)
A(_NET_WM_VISIBLE_NAME)
A(_NET_WM_STRUT)
A(_NET_WM_STRUT_PARTIAL)
A(_NET_WM_ICON)
A(_KDE_NET_WM_SYSTEM_TRAY_WINDOW_FOR)

/* SYSTEM TRAY spec */
//A(_NET_SYSTEM_TRAY_OPCODE)
//A(_NET_SYSTEM_TRAY_MESSAGE_DATA)
//A(_NET_SYSTEM_TRAY_ORIENTATION)
//A(MANAGER)

A(_MOTIF_WM_HINTS)

A(_WATERLINE_TEXT_CMD)

A(_OB_THEME)

